### ISSUE TITLE
Search doesn't appear to work

### ISSUE THREAD

**Issue by tbsp** [gbdev/virens#24]
No matter which combination of settings I use it says, "No data yet..".

This includes "game" type entries with all the general tags selected (platform, puzzle, rpg, etc).

Also, a text field to include in the search might be useful. The alternative I've found there is to use the page's sitemap and ctrl+f in my browser.

**Comment by avivace** [comment]
> No matter which combination of settings I use it says, "No data yet..".
> 
> This includes "game" type entries with all the general tags selected (platform, puzzle, rpg, etc).
> 
> Also, a text field to include in the search might be useful. The alternative I've found there is to use the page's sitemap and ctrl+f in my browser.

Hey @tbsp , thanks for the report. Something is definitely wrong with the deployment, looks like some API calls are broken. I'll investigate

**Comment by avivace** [comment]
The /search API endpoint was updated in https://github.com/gbdev/homebrewhub/commit/7db32ed6ff72c2283b45bf645476f5289b7e4ff4 to accept a query string filtering the title or the slug and https://github.com/gbdev/virens/commit/4f14eba76eab6dcd60d52f512fe26eb16b5b7445 introduced the new  input text query string on the frontend
