### ISSUE TITLE
"Improve metadata for this entry" always links to GB instead to GBA entries

### ISSUE THREAD

**Issue by tolik518** [gbdev/virens#36]
A homebrew page has a "Improve metadata for this entry" link that should link to the page with the metadata. 
This works only for GB games though, not for GBA games.

On the page of [Butano Fighter](https://hh.gbdev.io/game/butano-fighter) for example it links to
github.com/**gbdev**/database/tree/master/entries/butano-fighter/game.json
instead of to 
github.com/**gbadev-org**/database/tree/master/entries/butano-fighter/game.json

**Comment by avivace** [comment]
Thanks for the report @tolik518 ! Unfortunately the support for additional "data sources" is still a bit premature and I merged it before taking care of adapting the database schema for this, so atm the API doesn't really know from which upstream repository any entry is from (and frontend just default-guesses the gbdev/database one), the sync script must also be adapted for this.
I already reported this in https://github.com/gbdev/virens/issues/36 so I'm going to close this as duplicate but I plan to take care of it soon (tm).
